
default: &default
  adapter: mysql2
  encoding: utf8


development:
  <<: *default
  host: localhost
  username: root
  password: root
  database: invoice_uploader_development

test:
  <<: *default
  host: localhost
  username: root
  password: root
  database: invoice_uploader_test

production:
  <<: *default
